import { createContext, useContext, useState, ReactNode, useEffect } from "react"

export type Language = "en" | "zh" | "de" | "ru" | "ar" | "es" | "fr" | "pt" | "ja" | "ko" | "it" | "tr" | "hi" | "ur" | "nl"

interface LanguageInfo {
  code: Language
  name: string
  flag: string
  nativeName: string
}

export const languages: LanguageInfo[] = [
  { code: "en", name: "English", flag: "🇺🇸", nativeName: "English" },
  { code: "zh", name: "Chinese", flag: "🇨🇳", nativeName: "中文" },
  { code: "de", name: "German", flag: "🇩🇪", nativeName: "Deutsch" },
  { code: "ru", name: "Russian", flag: "🇷🇺", nativeName: "Русский" },
  { code: "ar", name: "Arabic", flag: "🇸🇦", nativeName: "العربية" },
  { code: "es", name: "Spanish", flag: "🇪🇸", nativeName: "Español" },
  { code: "fr", name: "French", flag: "🇫🇷", nativeName: "Français" },
  { code: "pt", name: "Portuguese", flag: "🇵🇹", nativeName: "Português" },
  { code: "ja", name: "Japanese", flag: "🇯🇵", nativeName: "日本語" },
  { code: "ko", name: "Korean", flag: "🇰🇷", nativeName: "한국어" },
  { code: "it", name: "Italian", flag: "🇮🇹", nativeName: "Italiano" },
  { code: "tr", name: "Turkish", flag: "🇹🇷", nativeName: "Türkçe" },
  { code: "hi", name: "Hindi", flag: "🇮🇳", nativeName: "हिन्दी" },
  { code: "ur", name: "Urdu", flag: "🇵🇰", nativeName: "اردو" },
  { code: "nl", name: "Dutch", flag: "🇳🇱", nativeName: "Nederlands" },
]

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
  getLanguageInfo: (code: Language) => LanguageInfo | undefined
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.skills": "Skills",
    "nav.projects": "Projects",
    "nav.whyme": "Why Me",
    "nav.about": "About",
    "nav.contact": "Contact",
    "hero.badge": "Available for Projects",
    "hero.title": "Hi, I'm Muhammad Salman",
    "hero.titleHighlight": "Android Developer",
    "hero.description": "Crafting beautiful and functional Android applications with modern technologies. Specialized in Kotlin, Jetpack Compose, Firebase, and building scalable mobile solutions.",
    "hero.primaryButton": "View My Projects",
    "hero.secondaryButton": "Contact Me",
    "hero.downloadResume": "Download Resume",
    "hero.viewResume": "View Resume",
    "hero.feature1": "3+ Years Experience",
    "hero.feature2": "20+ Published Apps",
    "skills.title": "Technologies & Tools",
    "skills.subtitle": "Modern tools and technologies I use to build exceptional Android applications",
    "projects.title": "Featured Projects",
    "projects.subtitle": "A showcase of my recent Android applications and mobile projects",
    "projects.button.github": "GitHub",
    "projects.button.playStore": "Play Store",
    "projects.button.details": "Details",
    "about.subtitle": "About Me",
    "about.title": "Why Choose Me",
    "about.description": "I bring years of experience in Android development, delivering high-quality mobile applications that exceed expectations.",
    "about.stats.publishedApps": "Published Apps",
    "about.stats.projectsCompleted": "Projects Completed",
    "about.stats.yearsExperience": "Years Experience",
    "about.stats.averageRating": "Average Rating",
    "process.title": "My Development Process",
    "process.subtitle": "A structured approach to delivering high-quality Android applications",
    "process.step1.title": "Discovery",
    "process.step1.description": "Understanding your requirements, target audience, and business goals through detailed consultation.",
    "process.step2.title": "Design",
    "process.step2.description": "Creating intuitive UI/UX designs and system architecture aligned with Material Design guidelines.",
    "process.step3.title": "Development",
    "process.step3.description": "Building robust, scalable Android applications using modern technologies and best practices.",
    "process.step4.title": "Deployment",
    "process.step4.description": "Thorough testing, Play Store submission, and ongoing maintenance and updates.",
    "reviews.title": "Client Testimonials",
    "reviews.subtitle": "What clients say about working with me",
    "contact.subtitle": "Get In Touch",
    "contact.title": "Have a project in mind? Let's build something amazing together.",
    "contact.description": "I'm always open to discussing new projects, creative ideas, or opportunities to be part of your visions.",
    "contact.formTitle": "Send Me a Message",
    "contact.label.name": "Name",
    "contact.label.email": "Email",
    "contact.label.message": "Message",
    "contact.placeholder.name": "Your name",
    "contact.placeholder.email": "your.email@example.com",
    "contact.placeholder.message": "Your message...",
    "contact.button.submit": "Send Message",
    "contact.button.sending": "Sending...",
    "contact.info.email": "Email",
    "contact.info.phone": "Phone",
    "contact.info.location": "Location",
    "footer.description": "Passionate Android developer creating innovative mobile solutions. Let's build the next great app together.",
    "footer.quickLinks": "Quick Links",
    "footer.links.whyme": "Why Me",
    "footer.links.about": "About",
    "footer.links.projects": "Projects",
    "footer.links.contact": "Contact",
    "footer.connect": "Connect",
    "footer.allRightsReserved": "All rights reserved.",
    "projectDetail.backToProjects": "Back to Projects",
    "projectDetail.notFound": "Project Not Found",
    "projectDetail.button.backToHome": "Back to Home",
    "projectDetail.button.viewOnGithub": "View on GitHub",
    "projectDetail.button.viewOnPlayStore": "View on Play Store",
    "projectDetail.features": "Features",
    "resume.backToHome": "Back to Home",
    "resume.download": "Download Resume",
  },
  zh: {
    "nav.skills": "技能",
    "nav.projects": "项目",
    "nav.whyme": "为什么选择我",
    "nav.about": "关于",
    "nav.contact": "联系",
    "hero.badge": "可承接项目",
    "hero.title": "你好，我是穆罕默德·萨勒曼",
    "hero.titleHighlight": "Android 开发者",
    "hero.description": "使用现代技术开发美观且功能强大的 Android 应用程序。专注于 Kotlin、Jetpack Compose、Firebase 和构建可扩展的移动解决方案。",
    "hero.primaryButton": "查看我的项目",
    "hero.secondaryButton": "联系我",
    "hero.downloadResume": "下载简历",
    "hero.viewResume": "查看简历",
    "hero.feature1": "3年以上经验",
    "hero.feature2": "20+已发布应用",
    "skills.title": "技术与工具",
    "skills.subtitle": "我用于构建卓越 Android 应用程序的现代工具和技术",
    "projects.title": "精选项目",
    "projects.subtitle": "展示我最近的 Android 应用程序和移动项目",
    "projects.button.github": "GitHub",
    "projects.button.playStore": "Play商店",
    "projects.button.details": "详情",
    "about.subtitle": "关于我",
    "about.title": "为什么选择我",
    "about.description": "我在 Android 开发方面拥有多年经验，提供超出预期的高质量移动应用程序。",
    "about.stats.publishedApps": "已发布应用",
    "about.stats.projectsCompleted": "已完成项目",
    "about.stats.yearsExperience": "年经验",
    "about.stats.averageRating": "平均评分",
    "process.title": "我的开发流程",
    "process.subtitle": "交付高质量 Android 应用程序的结构化方法",
    "process.step1.title": "发现",
    "process.step1.description": "通过详细咨询了解您的需求、目标受众和业务目标。",
    "process.step2.title": "设计",
    "process.step2.description": "创建符合 Material Design 指南的直观 UI/UX 设计和系统架构。",
    "process.step3.title": "开发",
    "process.step3.description": "使用现代技术和最佳实践构建强大、可扩展的 Android 应用程序。",
    "process.step4.title": "部署",
    "process.step4.description": "全面测试、Play商店提交以及持续的维护和更新。",
    "reviews.title": "客户评价",
    "reviews.subtitle": "客户对与我合作的评价",
    "contact.subtitle": "取得联系",
    "contact.title": "有项目想法吗？让我们一起构建一些令人惊叹的东西。",
    "contact.description": "我总是乐于讨论新项目、创意想法或成为您愿景一部分的机会。",
    "contact.formTitle": "给我发消息",
    "contact.label.name": "姓名",
    "contact.label.email": "电子邮件",
    "contact.label.message": "消息",
    "contact.placeholder.name": "您的姓名",
    "contact.placeholder.email": "your.email@example.com",
    "contact.placeholder.message": "您的消息...",
    "contact.button.submit": "发送消息",
    "contact.button.sending": "发送中...",
    "contact.info.email": "电子邮件",
    "contact.info.phone": "电话",
    "contact.info.location": "位置",
    "footer.description": "充满热情的 Android 开发者，创造创新的移动解决方案。让我们一起构建下一个伟大的应用程序。",
    "footer.quickLinks": "快速链接",
    "footer.links.whyme": "为什么选择我",
    "footer.links.about": "关于",
    "footer.links.projects": "项目",
    "footer.links.contact": "联系",
    "footer.connect": "联系",
    "footer.allRightsReserved": "版权所有。",
    "projectDetail.backToProjects": "返回项目",
    "projectDetail.notFound": "未找到项目",
    "projectDetail.button.backToHome": "返回首页",
    "projectDetail.button.viewOnGithub": "在 GitHub 上查看",
    "projectDetail.button.viewOnPlayStore": "在 Play商店查看",
    "projectDetail.features": "功能",
    "resume.backToHome": "返回首页",
    "resume.download": "下载简历",
  },
  de: {
    "nav.skills": "Fähigkeiten",
    "nav.projects": "Projekte",
    "nav.whyme": "Warum Mich",
    "nav.about": "Über",
    "nav.contact": "Kontakt",
    "hero.badge": "Verfügbar für Projekte",
    "hero.title": "Hallo, ich bin Muhammad Salman",
    "hero.titleHighlight": "Android-Entwickler",
    "hero.description": "Entwicklung schöner und funktionaler Android-Anwendungen mit modernen Technologien. Spezialisiert auf Kotlin, Jetpack Compose, Firebase und den Aufbau skalierbarer mobiler Lösungen.",
    "hero.primaryButton": "Meine Projekte ansehen",
    "hero.secondaryButton": "Kontaktieren Sie mich",
    "hero.downloadResume": "Lebenslauf herunterladen",
    "hero.viewResume": "Lebenslauf ansehen",
    "hero.feature1": "3+ Jahre Erfahrung",
    "hero.feature2": "20+ Veröffentlichte Apps",
    "skills.title": "Technologien & Tools",
    "skills.subtitle": "Moderne Tools und Technologien, die ich zum Erstellen außergewöhnlicher Android-Anwendungen verwende",
    "projects.title": "Ausgewählte Projekte",
    "projects.subtitle": "Eine Auswahl meiner neuesten Android-Anwendungen und mobilen Projekte",
    "projects.button.github": "GitHub",
    "projects.button.playStore": "Play Store",
    "projects.button.details": "Details",
    "about.subtitle": "Über Mich",
    "about.title": "Warum mich wählen",
    "about.description": "Ich bringe jahrelange Erfahrung in der Android-Entwicklung mit und liefere hochwertige mobile Anwendungen, die Erwartungen übertreffen.",
    "about.stats.publishedApps": "Veröffentlichte Apps",
    "about.stats.projectsCompleted": "Abgeschlossene Projekte",
    "about.stats.yearsExperience": "Jahre Erfahrung",
    "about.stats.averageRating": "Durchschnittliche Bewertung",
    "process.title": "Mein Entwicklungsprozess",
    "process.subtitle": "Ein strukturierter Ansatz zur Lieferung hochwertiger Android-Anwendungen",
    "process.step1.title": "Entdeckung",
    "process.step1.description": "Verständnis Ihrer Anforderungen, Zielgruppe und Geschäftsziele durch detaillierte Beratung.",
    "process.step2.title": "Design",
    "process.step2.description": "Erstellen intuitiver UI/UX-Designs und Systemarchitekturen, die an Material Design-Richtlinien ausgerichtet sind.",
    "process.step3.title": "Entwicklung",
    "process.step3.description": "Aufbau robuster, skalierbarer Android-Anwendungen mit modernen Technologien und bewährten Praktiken.",
    "process.step4.title": "Bereitstellung",
    "process.step4.description": "Gründliches Testen, Play Store-Einreichung sowie laufende Wartung und Updates.",
    "reviews.title": "Kundenbewertungen",
    "reviews.subtitle": "Was Kunden über die Zusammenarbeit mit mir sagen",
    "contact.subtitle": "Kontakt aufnehmen",
    "contact.title": "Haben Sie ein Projekt im Sinn? Lassen Sie uns gemeinsam etwas Großartiges aufbauen.",
    "contact.description": "Ich bin immer offen für die Diskussion neuer Projekte, kreativer Ideen oder Möglichkeiten, Teil Ihrer Visionen zu sein.",
    "contact.formTitle": "Senden Sie mir eine Nachricht",
    "contact.label.name": "Name",
    "contact.label.email": "E-Mail",
    "contact.label.message": "Nachricht",
    "contact.placeholder.name": "Ihr Name",
    "contact.placeholder.email": "ihre.email@beispiel.com",
    "contact.placeholder.message": "Ihre Nachricht...",
    "contact.button.submit": "Nachricht senden",
    "contact.button.sending": "Wird gesendet...",
    "contact.info.email": "E-Mail",
    "contact.info.phone": "Telefon",
    "contact.info.location": "Standort",
    "footer.description": "Leidenschaftlicher Android-Entwickler, der innovative mobile Lösungen schafft. Lassen Sie uns gemeinsam die nächste großartige App bauen.",
    "footer.quickLinks": "Schnelllinks",
    "footer.links.whyme": "Warum Mich",
    "footer.links.about": "Über",
    "footer.links.projects": "Projekte",
    "footer.links.contact": "Kontakt",
    "footer.connect": "Verbinden",
    "footer.allRightsReserved": "Alle Rechte vorbehalten.",
    "projectDetail.backToProjects": "Zurück zu Projekten",
    "projectDetail.notFound": "Projekt nicht gefunden",
    "projectDetail.button.backToHome": "Zurück zur Startseite",
    "projectDetail.button.viewOnGithub": "Auf GitHub ansehen",
    "projectDetail.button.viewOnPlayStore": "Im Play Store ansehen",
    "projectDetail.features": "Funktionen",
    "resume.backToHome": "Zurück zur Startseite",
    "resume.download": "Lebenslauf herunterladen",
  },
  ru: {
    "nav.skills": "Навыки",
    "nav.projects": "Проекты",
    "nav.whyme": "Почему Я",
    "nav.about": "О нас",
    "nav.contact": "Контакты",
    "hero.badge": "Доступен для проектов",
    "hero.title": "Привет, я Мухаммад Салман",
    "hero.titleHighlight": "Android-разработчик",
    "hero.description": "Создание красивых и функциональных Android-приложений с использованием современных технологий. Специализация: Kotlin, Jetpack Compose, Firebase и создание масштабируемых мобильных решений.",
    "hero.primaryButton": "Посмотреть мои проекты",
    "hero.secondaryButton": "Связаться со мной",
    "hero.downloadResume": "Скачать резюме",
    "hero.viewResume": "Просмотреть резюме",
    "hero.feature1": "3+ года опыта",
    "hero.feature2": "20+ опубликованных приложений",
    "skills.title": "Технологии и инструменты",
    "skills.subtitle": "Современные инструменты и технологии, которые я использую для создания исключительных Android-приложений",
    "projects.title": "Рекомендуемые проекты",
    "projects.subtitle": "Демонстрация моих недавних Android-приложений и мобильных проектов",
    "projects.button.github": "GitHub",
    "projects.button.playStore": "Play Store",
    "projects.button.details": "Детали",
    "about.subtitle": "Обо мне",
    "about.title": "Почему выбрать меня",
    "about.description": "Я имею многолетний опыт в разработке Android, предоставляя высококачественные мобильные приложения, которые превосходят ожидания.",
    "about.stats.publishedApps": "Опубликованные приложения",
    "about.stats.projectsCompleted": "Завершенные проекты",
    "about.stats.yearsExperience": "Лет опыта",
    "about.stats.averageRating": "Средний рейтинг",
    "process.title": "Мой процесс разработки",
    "process.subtitle": "Структурированный подход к предоставлению высококачественных Android-приложений",
    "process.step1.title": "Исследование",
    "process.step1.description": "Понимание ваших требований, целевой аудитории и бизнес-целей через детальную консультацию.",
    "process.step2.title": "Дизайн",
    "process.step2.description": "Создание интуитивных UI/UX-дизайнов и системной архитектуры, соответствующих принципам Material Design.",
    "process.step3.title": "Разработка",
    "process.step3.description": "Создание надежных, масштабируемых Android-приложений с использованием современных технологий и лучших практик.",
    "process.step4.title": "Развертывание",
    "process.step4.description": "Тщательное тестирование, отправка в Play Store и постоянное обслуживание и обновления.",
    "reviews.title": "Отзывы клиентов",
    "reviews.subtitle": "Что клиенты говорят о работе со мной",
    "contact.subtitle": "Связаться",
    "contact.title": "Есть проект? Давайте вместе создадим что-то удивительное.",
    "contact.description": "Я всегда открыт для обсуждения новых проектов, творческих идей или возможностей стать частью ваших видений.",
    "contact.formTitle": "Отправьте мне сообщение",
    "contact.label.name": "Имя",
    "contact.label.email": "Электронная почта",
    "contact.label.message": "Сообщение",
    "contact.placeholder.name": "Ваше имя",
    "contact.placeholder.email": "your.email@example.com",
    "contact.placeholder.message": "Ваше сообщение...",
    "contact.button.submit": "Отправить сообщение",
    "contact.button.sending": "Отправка...",
    "contact.info.email": "Электронная почта",
    "contact.info.phone": "Телефон",
    "contact.info.location": "Местоположение",
    "footer.description": "Увлеченный разработчик Android, создающий инновационные мобильные решения. Давайте вместе создадим следующее великое приложение.",
    "footer.quickLinks": "Быстрые ссылки",
    "footer.links.whyme": "Почему Я",
    "footer.links.about": "О нас",
    "footer.links.projects": "Проекты",
    "footer.links.contact": "Контакты",
    "footer.connect": "Связаться",
    "footer.allRightsReserved": "Все права защищены.",
    "projectDetail.backToProjects": "Назад к проектам",
    "projectDetail.notFound": "Проект не найден",
    "projectDetail.button.backToHome": "Назад на главную",
    "projectDetail.button.viewOnGithub": "Посмотреть на GitHub",
    "projectDetail.button.viewOnPlayStore": "Посмотреть в Play Store",
    "projectDetail.features": "Функции",
    "resume.backToHome": "Назад на главную",
    "resume.download": "Скачать резюме",
  },
  ar: {
    "nav.skills": "المهارات",
    "nav.projects": "المشاريع",
    "nav.whyme": "لماذا أنا",
    "nav.about": "نبذة",
    "nav.contact": "اتصل",
    "hero.badge": "متاح للمشاريع",
    "hero.title": "مرحباً، أنا محمد سلمان",
    "hero.titleHighlight": "مطور أندرويد",
    "hero.description": "إنشاء تطبيقات أندرويد جميلة ووظيفية باستخدام التقنيات الحديثة. متخصص في Kotlin و Jetpack Compose و Firebase وبناء حلول محمولة قابلة للتطوير.",
    "hero.primaryButton": "عرض مشاريعي",
    "hero.secondaryButton": "اتصل بي",
    "hero.downloadResume": "تحميل السيرة الذاتية",
    "hero.viewResume": "عرض السيرة الذاتية",
    "hero.feature1": "3+ سنوات من الخبرة",
    "hero.feature2": "20+ تطبيق منشور",
    "skills.title": "التقنيات والأدوات",
    "skills.subtitle": "أدوات وتقنيات حديثة أستخدمها لبناء تطبيقات أندرويد استثنائية",
    "projects.title": "المشاريع المميزة",
    "projects.subtitle": "عرض لتطبيقات أندرويد ومشاريعي النقالة الحديثة",
    "projects.button.github": "GitHub",
    "projects.button.playStore": "Play Store",
    "projects.button.details": "التفاصيل",
    "about.subtitle": "عني",
    "about.title": "لماذا تختارني",
    "about.description": "لدي سنوات من الخبرة في تطوير أندرويد، وأقدم تطبيقات محمولة عالية الجودة تتجاوز التوقعات.",
    "about.stats.publishedApps": "تطبيقات منشورة",
    "about.stats.projectsCompleted": "مشاريع مكتملة",
    "about.stats.yearsExperience": "سنوات من الخبرة",
    "about.stats.averageRating": "التقييم المتوسط",
    "process.title": "عملية التطوير الخاصة بي",
    "process.subtitle": "نهج منظم لتقديم تطبيقات أندرويد عالية الجودة",
    "process.step1.title": "الاكتشاف",
    "process.step1.description": "فهم متطلباتك وجمهورك المستهدف وأهداف عملك من خلال استشارة مفصلة.",
    "process.step2.title": "التصميم",
    "process.step2.description": "إنشاء تصاميم وواجهات مستخدم بديهية وهندسة معمارية للنظام تتماشى مع إرشادات Material Design.",
    "process.step3.title": "التطوير",
    "process.step3.description": "بناء تطبيقات أندرويد قوية وقابلة للتطوير باستخدام تقنيات حديثة وأفضل الممارسات.",
    "process.step4.title": "النشر",
    "process.step4.description": "اختبار شامل وتقديم إلى Play Store وصيانة مستمرة وتحديثات.",
    "reviews.title": "شهادات العملاء",
    "reviews.subtitle": "ماذا يقول العملاء عن العمل معي",
    "contact.subtitle": "تواصل معنا",
    "contact.title": "هل لديك مشروع في الاعتبار؟ دعنا نبني شيئاً رائعاً معاً.",
    "contact.description": "أنا منفتح دائماً لمناقشة مشاريع جديدة أو أفكار إبداعية أو فرص لأن أكون جزءاً من رؤاك.",
    "contact.formTitle": "أرسل لي رسالة",
    "contact.label.name": "الاسم",
    "contact.label.email": "البريد الإلكتروني",
    "contact.label.message": "الرسالة",
    "contact.placeholder.name": "اسمك",
    "contact.placeholder.email": "your.email@example.com",
    "contact.placeholder.message": "رسالتك...",
    "contact.button.submit": "إرسال الرسالة",
    "contact.button.sending": "جارٍ الإرسال...",
    "contact.info.email": "البريد الإلكتروني",
    "contact.info.phone": "الهاتف",
    "contact.info.location": "الموقع",
    "footer.description": "مطور أندرويد شغوف بإنشاء حلول محمولة مبتكرة. دعنا نبني التطبيق العظيم التالي معاً.",
    "footer.quickLinks": "روابط سريعة",
    "footer.links.whyme": "لماذا أنا",
    "footer.links.about": "نبذة",
    "footer.links.projects": "المشاريع",
    "footer.links.contact": "اتصل",
    "footer.connect": "تواصل",
    "footer.allRightsReserved": "جميع الحقوق محفوظة.",
    "projectDetail.backToProjects": "العودة إلى المشاريع",
    "projectDetail.notFound": "المشروع غير موجود",
    "projectDetail.button.backToHome": "العودة إلى الصفحة الرئيسية",
    "projectDetail.button.viewOnGithub": "عرض على GitHub",
    "projectDetail.button.viewOnPlayStore": "عرض على Play Store",
    "projectDetail.features": "المميزات",
    "resume.backToHome": "العودة إلى الصفحة الرئيسية",
    "resume.download": "تحميل السيرة الذاتية",
  },
  es: {
    "nav.skills": "Habilidades",
    "nav.projects": "Proyectos",
    "nav.whyme": "Por Qué Yo",
    "nav.about": "Acerca de",
    "nav.contact": "Contacto",
    "hero.badge": "Disponible para Proyectos",
    "hero.title": "Hola, soy Muhammad Salman",
    "hero.titleHighlight": "Desarrollador Android",
    "hero.description": "Creando aplicaciones Android hermosas y funcionales con tecnologías modernas. Especializado en Kotlin, Jetpack Compose, Firebase y construcción de soluciones móviles escalables.",
    "hero.primaryButton": "Ver Mis Proyectos",
    "hero.secondaryButton": "Contáctame",
    "hero.downloadResume": "Descargar Currículum",
    "hero.viewResume": "Ver Currículum",
    "hero.feature1": "3+ Años de Experiencia",
    "hero.feature2": "20+ Aplicaciones Publicadas",
    "skills.title": "Tecnologías y Herramientas",
    "skills.subtitle": "Herramientas y tecnologías modernas que uso para construir aplicaciones Android excepcionales",
    "projects.title": "Proyectos Destacados",
    "projects.subtitle": "Una muestra de mis recientes aplicaciones Android y proyectos móviles",
    "projects.button.github": "GitHub",
    "projects.button.playStore": "Play Store",
    "projects.button.details": "Detalles",
    "about.subtitle": "Acerca de Mí",
    "about.title": "Por Qué Elegirme",
    "about.description": "Tengo años de experiencia en desarrollo Android, entregando aplicaciones móviles de alta calidad que superan las expectativas.",
    "about.stats.publishedApps": "Aplicaciones Publicadas",
    "about.stats.projectsCompleted": "Proyectos Completados",
    "about.stats.yearsExperience": "Años de Experiencia",
    "about.stats.averageRating": "Calificación Promedio",
    "process.title": "Mi Proceso de Desarrollo",
    "process.subtitle": "Un enfoque estructurado para entregar aplicaciones Android de alta calidad",
    "process.step1.title": "Descubrimiento",
    "process.step1.description": "Comprender sus requisitos, audiencia objetivo y objetivos comerciales a través de una consultoría detallada.",
    "process.step2.title": "Diseño",
    "process.step2.description": "Crear diseños UI/UX intuitivos y arquitectura de sistema alineados con las pautas de Material Design.",
    "process.step3.title": "Desarrollo",
    "process.step3.description": "Construir aplicaciones Android robustas y escalables usando tecnologías modernas y mejores prácticas.",
    "process.step4.title": "Implementación",
    "process.step4.description": "Pruebas exhaustivas, envío a Play Store y mantenimiento y actualizaciones continuas.",
    "reviews.title": "Testimonios de Clientes",
    "reviews.subtitle": "Lo que dicen los clientes sobre trabajar conmigo",
    "contact.subtitle": "Ponerse en Contacto",
    "contact.title": "¿Tienes un proyecto en mente? Construyamos algo increíble juntos.",
    "contact.description": "Siempre estoy abierto a discutir nuevos proyectos, ideas creativas u oportunidades para ser parte de sus visiones.",
    "contact.formTitle": "Envíame un Mensaje",
    "contact.label.name": "Nombre",
    "contact.label.email": "Correo Electrónico",
    "contact.label.message": "Mensaje",
    "contact.placeholder.name": "Tu nombre",
    "contact.placeholder.email": "tu.email@ejemplo.com",
    "contact.placeholder.message": "Tu mensaje...",
    "contact.button.submit": "Enviar Mensaje",
    "contact.button.sending": "Enviando...",
    "contact.info.email": "Correo Electrónico",
    "contact.info.phone": "Teléfono",
    "contact.info.location": "Ubicación",
    "footer.description": "Desarrollador Android apasionado creando soluciones móviles innovadoras. Construyamos la próxima gran aplicación juntos.",
    "footer.quickLinks": "Enlaces Rápidos",
    "footer.links.whyme": "Por Qué Yo",
    "footer.links.about": "Acerca de",
    "footer.links.projects": "Proyectos",
    "footer.links.contact": "Contacto",
    "footer.connect": "Conectar",
    "footer.allRightsReserved": "Todos los derechos reservados.",
    "projectDetail.backToProjects": "Volver a Proyectos",
    "projectDetail.notFound": "Proyecto No Encontrado",
    "projectDetail.button.backToHome": "Volver al Inicio",
    "projectDetail.button.viewOnGithub": "Ver en GitHub",
    "projectDetail.button.viewOnPlayStore": "Ver en Play Store",
    "projectDetail.features": "Características",
    "resume.backToHome": "Volver al Inicio",
    "resume.download": "Descargar Currículum",
  },
  fr: {
    "nav.skills": "Compétences",
    "nav.projects": "Projets",
    "nav.whyme": "Pourquoi Moi",
    "nav.about": "À propos",
    "nav.contact": "Contact",
    "hero.badge": "Disponible pour Projets",
    "hero.title": "Bonjour, je suis Muhammad Salman",
    "hero.titleHighlight": "Développeur Android",
    "hero.description": "Création d'applications Android belles et fonctionnelles avec des technologies modernes. Spécialisé en Kotlin, Jetpack Compose, Firebase et construction de solutions mobiles évolutives.",
    "hero.primaryButton": "Voir Mes Projets",
    "hero.secondaryButton": "Me Contacter",
    "hero.downloadResume": "Télécharger CV",
    "hero.viewResume": "Voir CV",
    "hero.feature1": "3+ Années d'Expérience",
    "hero.feature2": "20+ Applications Publiées",
    "skills.title": "Technologies et Outils",
    "skills.subtitle": "Outils et technologies modernes que j'utilise pour créer des applications Android exceptionnelles",
    "projects.title": "Projets Sélectionnés",
    "projects.subtitle": "Une vitrine de mes récentes applications Android et projets mobiles",
    "projects.button.github": "GitHub",
    "projects.button.playStore": "Play Store",
    "projects.button.details": "Détails",
    "about.subtitle": "À Propos de Moi",
    "about.title": "Pourquoi Me Choisir",
    "about.description": "J'apporte des années d'expérience en développement Android, livrant des applications mobiles de haute qualité qui dépassent les attentes.",
    "about.stats.publishedApps": "Applications Publiées",
    "about.stats.projectsCompleted": "Projets Complétés",
    "about.stats.yearsExperience": "Années d'Expérience",
    "about.stats.averageRating": "Note Moyenne",
    "process.title": "Mon Processus de Développement",
    "process.subtitle": "Une approche structurée pour livrer des applications Android de haute qualité",
    "process.step1.title": "Découverte",
    "process.step1.description": "Comprendre vos exigences, votre public cible et vos objectifs commerciaux grâce à une consultation détaillée.",
    "process.step2.title": "Conception",
    "process.step2.description": "Créer des conceptions UI/UX intuitives et une architecture système alignées sur les lignes directrices de Material Design.",
    "process.step3.title": "Développement",
    "process.step3.description": "Construire des applications Android robustes et évolutives en utilisant des technologies modernes et les meilleures pratiques.",
    "process.step4.title": "Déploiement",
    "process.step4.description": "Tests approfondis, soumission au Play Store et maintenance continue et mises à jour.",
    "reviews.title": "Témoignages Clients",
    "reviews.subtitle": "Ce que disent les clients de travailler avec moi",
    "contact.subtitle": "Prendre Contact",
    "contact.title": "Vous avez un projet en tête ? Créons ensemble quelque chose d'extraordinaire.",
    "contact.description": "Je suis toujours ouvert à discuter de nouveaux projets, d'idées créatives ou d'opportunités pour faire partie de vos visions.",
    "contact.formTitle": "Envoyez-moi un Message",
    "contact.label.name": "Nom",
    "contact.label.email": "E-mail",
    "contact.label.message": "Message",
    "contact.placeholder.name": "Votre nom",
    "contact.placeholder.email": "votre.email@exemple.com",
    "contact.placeholder.message": "Votre message...",
    "contact.button.submit": "Envoyer le Message",
    "contact.button.sending": "Envoi en cours...",
    "contact.info.email": "E-mail",
    "contact.info.phone": "Téléphone",
    "contact.info.location": "Localisation",
    "footer.description": "Développeur Android passionné créant des solutions mobiles innovantes. Créons ensemble la prochaine grande application.",
    "footer.quickLinks": "Liens Rapides",
    "footer.links.whyme": "Pourquoi Moi",
    "footer.links.about": "À propos",
    "footer.links.projects": "Projets",
    "footer.links.contact": "Contact",
    "footer.connect": "Connecter",
    "footer.allRightsReserved": "Tous droits réservés.",
    "projectDetail.backToProjects": "Retour aux Projets",
    "projectDetail.notFound": "Projet Non Trouvé",
    "projectDetail.button.backToHome": "Retour à l'Accueil",
    "projectDetail.button.viewOnGithub": "Voir sur GitHub",
    "projectDetail.button.viewOnPlayStore": "Voir sur Play Store",
    "projectDetail.features": "Fonctionnalités",
    "resume.backToHome": "Retour à l'Accueil",
    "resume.download": "Télécharger le CV",
  },
  pt: {
    "nav.skills": "Habilidades",
    "nav.projects": "Projetos",
    "nav.whyme": "Por Que Eu",
    "nav.about": "Sobre",
    "nav.contact": "Contato",
    "hero.badge": "Disponível para Projetos",
    "hero.title": "Olá, eu sou Muhammad Salman",
    "hero.titleHighlight": "Desenvolvedor Android",
    "hero.description": "Criando aplicativos Android bonitos e funcionais com tecnologias modernas. Especializado em Kotlin, Jetpack Compose, Firebase e construção de soluções móveis escaláveis.",
    "hero.primaryButton": "Ver Meus Projetos",
    "hero.secondaryButton": "Entre em Contato",
    "hero.downloadResume": "Baixar Currículo",
    "hero.viewResume": "Ver Currículo",
    "hero.feature1": "3+ Anos de Experiência",
    "hero.feature2": "20+ Aplicativos Publicados",
    "skills.title": "Tecnologias e Ferramentas",
    "skills.subtitle": "Ferramentas e tecnologias modernas que uso para criar aplicativos Android excepcionais",
    "projects.title": "Projetos em Destaque",
    "projects.subtitle": "Uma vitrine dos meus recentes aplicativos Android e projetos móveis",
    "projects.button.github": "GitHub",
    "projects.button.playStore": "Play Store",
    "projects.button.details": "Detalhes",
    "about.subtitle": "Sobre Mim",
    "about.title": "Por Que Me Escolher",
    "about.description": "Tenho anos de experiência em desenvolvimento Android, entregando aplicativos móveis de alta qualidade que superam as expectativas.",
    "about.stats.publishedApps": "Aplicativos Publicados",
    "about.stats.projectsCompleted": "Projetos Completados",
    "about.stats.yearsExperience": "Anos de Experiência",
    "about.stats.averageRating": "Avaliação Média",
    "process.title": "Meu Processo de Desenvolvimento",
    "process.subtitle": "Uma abordagem estruturada para entregar aplicativos Android de alta qualidade",
    "process.step1.title": "Descoberta",
    "process.step1.description": "Entender seus requisitos, público-alvo e objetivos de negócios através de consultoria detalhada.",
    "process.step2.title": "Design",
    "process.step2.description": "Criar designs UI/UX intuitivos e arquitetura de sistema alinhados com as diretrizes do Material Design.",
    "process.step3.title": "Desenvolvimento",
    "process.step3.description": "Construir aplicativos Android robustos e escaláveis usando tecnologias modernas e melhores práticas.",
    "process.step4.title": "Implantaçã",
    "process.step4.description": "Testes rigorosos, submissão à Play Store e manutenção contínua e atualizações.",
    "reviews.title": "Depoimentos de Clientes",
    "reviews.subtitle": "O que os clientes dizem sobre trabalhar comigo",
    "contact.subtitle": "Entre em Contato",
    "contact.title": "Tem um projeto em mente? Vamos criar algo incrível juntos.",
    "contact.description": "Estou sempre aberto para discutir novos projetos, ideias criativas ou oportunidades para fazer parte das suas visões.",
    "contact.formTitle": "Envie-me uma Mensagem",
    "contact.label.name": "Nome",
    "contact.label.email": "E-mail",
    "contact.label.message": "Mensagem",
    "contact.placeholder.name": "Seu nome",
    "contact.placeholder.email": "seu.email@exemplo.com",
    "contact.placeholder.message": "Sua mensagem...",
    "contact.button.submit": "Enviar Mensagem",
    "contact.button.sending": "Enviando...",
    "contact.info.email": "E-mail",
    "contact.info.phone": "Telefone",
    "contact.info.location": "Localização",
    "footer.description": "Desenvolvedor Android apaixonado criando soluções móveis inovadoras. Vamos construir o próximo grande aplicativo juntos.",
    "footer.quickLinks": "Links Rápidos",
    "footer.links.whyme": "Por Que Eu",
    "footer.links.about": "Sobre",
    "footer.links.projects": "Projetos",
    "footer.links.contact": "Contato",
    "footer.connect": "Conectar",
    "footer.allRightsReserved": "Todos os direitos reservados.",
    "projectDetail.backToProjects": "Voltar aos Projetos",
    "projectDetail.notFound": "Projeto Não Encontrado",
    "projectDetail.button.backToHome": "Voltar ao Início",
    "projectDetail.button.viewOnGithub": "Ver no GitHub",
    "projectDetail.button.viewOnPlayStore": "Ver na Play Store",
    "projectDetail.features": "Recursos",
    "resume.backToHome": "Voltar ao Início",
    "resume.download": "Baixar Currículo",
  },
  ja: {
    "nav.skills": "スキル",
    "nav.projects": "プロジェクト",
    "nav.whyme": "なぜ私を選ぶ",
    "nav.about": "について",
    "nav.contact": "連絡先",
    "hero.badge": "プロジェクト対応可能",
    "hero.title": "こんにちは、私はムハンマド・サルマンです",
    "hero.titleHighlight": "Android開発者",
    "hero.description": "モダンなテクノロジーを使用して、美しく機能的なAndroidアプリケーションを作成します。Kotlin、Jetpack Compose、Firebase、スケーラブルなモバイルソリューションの構築に特化しています。",
    "hero.primaryButton": "プロジェクトを見る",
    "hero.secondaryButton": "お問い合わせ",
    "hero.downloadResume": "履歴書をダウンロード",
    "hero.viewResume": "履歴書を見る",
    "hero.feature1": "3年以上の経験",
    "hero.feature2": "20+公開済みアプリ",
    "skills.title": "技術とツール",
    "skills.subtitle": "優れたAndroidアプリケーションを構築するために使用するモダンなツールと技術",
    "projects.title": "注目のプロジェクト",
    "projects.subtitle": "最近のAndroidアプリケーションとモバイルプロジェクトの展示",
    "projects.button.github": "GitHub",
    "projects.button.playStore": "Play Store",
    "projects.button.details": "詳細",
    "about.subtitle": "私について",
    "about.title": "私を選ぶ理由",
    "about.description": "Android開発において何年もの経験を持ち、期待を超える高品質なモバイルアプリケーションを提供しています。",
    "about.stats.publishedApps": "公開済みアプリ",
    "about.stats.projectsCompleted": "完了したプロジェクト",
    "about.stats.yearsExperience": "年の経験",
    "about.stats.averageRating": "平均評価",
    "process.title": "私の開発プロセス",
    "process.subtitle": "高品質なAndroidアプリケーションを提供するための構造化されたアプローチ",
    "process.step1.title": "発見",
    "process.step1.description": "詳細な相談を通じて、要件、ターゲットオーディエンス、ビジネス目標を理解します。",
    "process.step2.title": "デザイン",
    "process.step2.description": "Material Designガイドラインに準拠した直感的なUI/UXデザインとシステムアーキテクチャを作成します。",
    "process.step3.title": "開発",
    "process.step3.description": "モダンな技術とベストプラクティスを使用して、堅牢でスケーラブルなAndroidアプリケーションを構築します。",
    "process.step4.title": "展開",
    "process.step4.description": "徹底的なテスト、Play Storeへの提出、継続的なメンテナンスと更新。",
    "reviews.title": "クライアントの推薦状",
    "reviews.subtitle": "クライアントが私との仕事について言っていること",
    "contact.subtitle": "お問い合わせ",
    "contact.title": "プロジェクトをお考えですか？一緒に素晴らしいものを作りましょう。",
    "contact.description": "新しいプロジェクト、創造的なアイデア、またはあなたのビジョンの一部になる機会について議論するために常にオープンです。",
    "contact.formTitle": "メッセージを送信",
    "contact.label.name": "名前",
    "contact.label.email": "メール",
    "contact.label.message": "メッセージ",
    "contact.placeholder.name": "お名前",
    "contact.placeholder.email": "your.email@example.com",
    "contact.placeholder.message": "メッセージ...",
    "contact.button.submit": "メッセージを送信",
    "contact.button.sending": "送信中...",
    "contact.info.email": "メール",
    "contact.info.phone": "電話",
    "contact.info.location": "場所",
    "footer.description": "革新的なモバイルソリューションを作成する情熱的なAndroid開発者。一緒に次の素晴らしいアプリを構築しましょう。",
    "footer.quickLinks": "クイックリンク",
    "footer.links.whyme": "なぜ私を選ぶ",
    "footer.links.about": "について",
    "footer.links.projects": "プロジェクト",
    "footer.links.contact": "連絡先",
    "footer.connect": "接続",
    "footer.allRightsReserved": "全著作権所有。",
    "projectDetail.backToProjects": "プロジェクトに戻る",
    "projectDetail.notFound": "プロジェクトが見つかりません",
    "projectDetail.button.backToHome": "ホームに戻る",
    "projectDetail.button.viewOnGithub": "GitHubで見る",
    "projectDetail.button.viewOnPlayStore": "Play Storeで見る",
    "projectDetail.features": "機能",
    "resume.backToHome": "ホームに戻る",
    "resume.download": "履歴書をダウンロード",
  },
  ko: {
    "nav.skills": "기술",
    "nav.projects": "프로젝트",
    "nav.whyme": "왜 저를 선택해야 할까요",
    "nav.about": "소개",
    "nav.contact": "연락처",
    "hero.badge": "프로젝트 가능",
    "hero.title": "안녕하세요, 저는 무하마드 살만입니다",
    "hero.titleHighlight": "Android 개발자",
    "hero.description": "현대 기술로 아름답고 기능적인 Android 애플리케이션을 제작합니다. Kotlin, Jetpack Compose, Firebase 및 확장 가능한 모바일 솔루션 구축 전문.",
    "hero.primaryButton": "프로젝트 보기",
    "hero.secondaryButton": "연락하기",
    "hero.downloadResume": "이력서 다운로드",
    "hero.viewResume": "이력서 보기",
    "hero.feature1": "3년 이상 경험",
    "hero.feature2": "20+ 출시된 앱",
    "skills.title": "기술 및 도구",
    "skills.subtitle": "탁월한 Android 애플리케이션을 구축하기 위해 사용하는 현대적인 도구 및 기술",
    "projects.title": "주요 프로젝트",
    "projects.subtitle": "최근 Android 애플리케이션 및 모바일 프로젝트 전시",
    "projects.button.github": "GitHub",
    "projects.button.playStore": "Play Store",
    "projects.button.details": "세부 정보",
    "about.subtitle": "저에 대해",
    "about.title": "저를 선택하는 이유",
    "about.description": "Android 개발 분야에서 수년간의 경험을 바탕으로 기대를 뛰어넘는 고품질 모바일 애플리케이션을 제공합니다.",
    "about.stats.publishedApps": "출시된 앱",
    "about.stats.projectsCompleted": "완료된 프로젝트",
    "about.stats.yearsExperience": "년 경험",
    "about.stats.averageRating": "평균 평점",
    "process.title": "제 개발 프로세스",
    "process.subtitle": "고품질 Android 애플리케이션을 제공하기 위한 구조화된 접근 방식",
    "process.step1.title": "발견",
    "process.step1.description": "상세한 상담을 통해 요구사항, 대상 고객 및 비즈니스 목표를 이해합니다.",
    "process.step2.title": "디자인",
    "process.step2.description": "Material Design 가이드라인에 맞춘 직관적인 UI/UX 디자인 및 시스템 아키텍처를 만듭니다.",
    "process.step3.title": "개발",
    "process.step3.description": "현대 기술과 모범 사례를 사용하여 강력하고 확장 가능한 Android 애플리케이션을 구축합니다.",
    "process.step4.title": "배포",
    "process.step4.description": "철저한 테스트, Play Store 제출, 지속적인 유지보수 및 업데이트.",
    "reviews.title": "고객 추천",
    "reviews.subtitle": "고객들이 저와 함께 일하는 것에 대해 말하는 것",
    "contact.subtitle": "연락하기",
    "contact.title": "프로젝트를 고려하고 계신가요? 함께 멋진 것을 만들어 봅시다.",
    "contact.description": "새로운 프로젝트, 창의적인 아이디어 또는 여러분의 비전의 일부가 될 기회에 대해 항상 열려 있습니다.",
    "contact.formTitle": "메시지 보내기",
    "contact.label.name": "이름",
    "contact.label.email": "이메일",
    "contact.label.message": "메시지",
    "contact.placeholder.name": "귀하의 이름",
    "contact.placeholder.email": "your.email@example.com",
    "contact.placeholder.message": "메시지...",
    "contact.button.submit": "메시지 보내기",
    "contact.button.sending": "전송 중...",
    "contact.info.email": "이메일",
    "contact.info.phone": "전화",
    "contact.info.location": "위치",
    "footer.description": "혁신적인 모바일 솔루션을 만드는 열정적인 Android 개발자. 함께 다음 훌륭한 앱을 만들어 봅시다.",
    "footer.quickLinks": "빠른 링크",
    "footer.links.whyme": "왜 저를 선택해야 할까요",
    "footer.links.about": "소개",
    "footer.links.projects": "프로젝트",
    "footer.links.contact": "연락처",
    "footer.connect": "연결",
    "footer.allRightsReserved": "모든 권리 보유.",
    "projectDetail.backToProjects": "프로젝트로 돌아가기",
    "projectDetail.notFound": "프로젝트를 찾을 수 없음",
    "projectDetail.button.backToHome": "홈으로 돌아가기",
    "projectDetail.button.viewOnGithub": "GitHub에서 보기",
    "projectDetail.button.viewOnPlayStore": "Play Store에서 보기",
    "projectDetail.features": "기능",
    "resume.backToHome": "홈으로 돌아가기",
    "resume.download": "이력서 다운로드",
  },
  it: {
    "nav.skills": "Competenze",
    "nav.projects": "Progetti",
    "nav.whyme": "Perché Me",
    "nav.about": "Chi Sono",
    "nav.contact": "Contatti",
    "hero.badge": "Disponibile per Progetti",
    "hero.title": "Ciao, sono Muhammad Salman",
    "hero.titleHighlight": "Sviluppatore Android",
    "hero.description": "Creazione di applicazioni Android belle e funzionali con tecnologie moderne. Specializzato in Kotlin, Jetpack Compose, Firebase e costruzione di soluzioni mobili scalabili.",
    "hero.primaryButton": "Vedi i Miei Progetti",
    "hero.secondaryButton": "Contattami",
    "hero.downloadResume": "Scarica Curriculum",
    "hero.viewResume": "Vedi Curriculum",
    "hero.feature1": "3+ Anni di Esperienza",
    "hero.feature2": "20+ App Pubblicate",
    "skills.title": "Tecnologie e Strumenti",
    "skills.subtitle": "Strumenti e tecnologie moderne che uso per creare applicazioni Android eccezionali",
    "projects.title": "Progetti in Evidenza",
    "projects.subtitle": "Una vetrina delle mie recenti applicazioni Android e progetti mobili",
    "projects.button.github": "GitHub",
    "projects.button.playStore": "Play Store",
    "projects.button.details": "Dettagli",
    "about.subtitle": "Su di Me",
    "about.title": "Perché Scegliermi",
    "about.description": "Porto anni di esperienza nello sviluppo Android, fornendo applicazioni mobili di alta qualità che superano le aspettative.",
    "about.stats.publishedApps": "App Pubblicate",
    "about.stats.projectsCompleted": "Progetti Completati",
    "about.stats.yearsExperience": "Anni di Esperienza",
    "about.stats.averageRating": "Valutazione Media",
    "process.title": "Il Mio Processo di Sviluppo",
    "process.subtitle": "Un approccio strutturato per fornire applicazioni Android di alta qualità",
    "process.step1.title": "Scoperta",
    "process.step1.description": "Comprendere i tuoi requisiti, il pubblico target e gli obiettivi aziendali attraverso una consultazione dettagliata.",
    "process.step2.title": "Design",
    "process.step2.description": "Creare design UI/UX intuitivi e architetture di sistema allineate alle linee guida Material Design.",
    "process.step3.title": "Sviluppo",
    "process.step3.description": "Costruire applicazioni Android robuste e scalabili utilizzando tecnologie moderne e migliori pratiche.",
    "process.step4.title": "Distribuzione",
    "process.step4.description": "Test approfonditi, invio al Play Store e manutenzione continua e aggiornamenti.",
    "reviews.title": "Testimonianze dei Clienti",
    "reviews.subtitle": "Cosa dicono i clienti di lavorare con me",
    "contact.subtitle": "Mettiamoci in Contatto",
    "contact.title": "Hai un progetto in mente? Creiamo qualcosa di straordinario insieme.",
    "contact.description": "Sono sempre aperto a discutere nuovi progetti, idee creative o opportunità per far parte delle tue visioni.",
    "contact.formTitle": "Inviami un Messaggio",
    "contact.label.name": "Nome",
    "contact.label.email": "E-mail",
    "contact.label.message": "Messaggio",
    "contact.placeholder.name": "Il tuo nome",
    "contact.placeholder.email": "your.email@esempio.com",
    "contact.placeholder.message": "Il tuo messaggio...",
    "contact.button.submit": "Invia Messaggio",
    "contact.button.sending": "Invio in corso...",
    "contact.info.email": "E-mail",
    "contact.info.phone": "Telefono",
    "contact.info.location": "Posizione",
    "footer.description": "Sviluppatore Android appassionato che crea soluzioni mobili innovative. Costruiamo insieme la prossima grande app.",
    "footer.quickLinks": "Collegamenti Rapidi",
    "footer.links.whyme": "Perché Me",
    "footer.links.about": "Chi Sono",
    "footer.links.projects": "Progetti",
    "footer.links.contact": "Contatti",
    "footer.connect": "Connetti",
    "footer.allRightsReserved": "Tutti i diritti riservati.",
    "projectDetail.backToProjects": "Torna ai Progetti",
    "projectDetail.notFound": "Progetto Non Trovato",
    "projectDetail.button.backToHome": "Torna alla Home",
    "projectDetail.button.viewOnGithub": "Vedi su GitHub",
    "projectDetail.button.viewOnPlayStore": "Vedi su Play Store",
    "projectDetail.features": "Funzionalità",
    "resume.backToHome": "Torna alla Home",
    "resume.download": "Scarica Curriculum",
  },
  tr: {
    "nav.skills": "Yetenekler",
    "nav.projects": "Projeler",
    "nav.whyme": "Neden Ben",
    "nav.about": "Hakkında",
    "nav.contact": "İletişim",
    "hero.badge": "Projeler İçin Müsait",
    "hero.title": "Merhaba, ben Muhammad Salman",
    "hero.titleHighlight": "Android Geliştirici",
    "hero.description": "Modern teknolojilerle güzel ve işlevsel Android uygulamaları oluşturma. Kotlin, Jetpack Compose, Firebase ve ölçeklenebilir mobil çözümler oluşturma konusunda uzman.",
    "hero.primaryButton": "Projelerimi Görüntüle",
    "hero.secondaryButton": "Bana Ulaşın",
    "hero.downloadResume": "Özgeçmiş İndir",
    "hero.viewResume": "Özgeçmiş Görüntüle",
    "hero.feature1": "3+ Yıl Deneyim",
    "hero.feature2": "20+ Yayınlanan Uygulama",
    "skills.title": "Teknolojiler ve Araçlar",
    "skills.subtitle": "Olağanüstü Android uygulamaları oluşturmak için kullandığım modern araçlar ve teknolojiler",
    "projects.title": "Öne Çıkan Projeler",
    "projects.subtitle": "Son Android uygulamalarım ve mobil projelerimin bir vitrini",
    "projects.button.github": "GitHub",
    "projects.button.playStore": "Play Store",
    "projects.button.details": "Detaylar",
    "about.subtitle": "Hakkımda",
    "about.title": "Beni Neden Seçmelisiniz",
    "about.description": "Android geliştirmede yıllarca deneyime sahibim, beklentileri aşan yüksek kaliteli mobil uygulamalar sunuyorum.",
    "about.stats.publishedApps": "Yayınlanan Uygulamalar",
    "about.stats.projectsCompleted": "Tamamlanan Projeler",
    "about.stats.yearsExperience": "Yıl Deneyim",
    "about.stats.averageRating": "Ortalama Değerlendirme",
    "process.title": "Geliştirme Sürecim",
    "process.subtitle": "Yüksek kaliteli Android uygulamaları sunmak için yapılandırılmış bir yaklaşım",
    "process.step1.title": "Keşif",
    "process.step1.description": "Detaylı danışmanlık yoluyla gereksinimlerinizi, hedef kitlenizi ve iş hedeflerinizi anlama.",
    "process.step2.title": "Tasarım",
    "process.step2.description": "Material Design yönergeleriyle uyumlu sezgisel UI/UX tasarımları ve sistem mimarisi oluşturma.",
    "process.step3.title": "Geliştirme",
    "process.step3.description": "Modern teknolojiler ve en iyi uygulamaları kullanarak sağlam, ölçeklenebilir Android uygulamaları oluşturma.",
    "process.step4.title": "Dağıtım",
    "process.step4.description": "Kapsamlı test, Play Store gönderimi ve sürekli bakım ve güncellemeler.",
    "reviews.title": "Müşteri Görüşleri",
    "reviews.subtitle": "Müşterilerin benimle çalışmak hakkında söyledikleri",
    "contact.subtitle": "İletişime Geçin",
    "contact.title": "Aklınızda bir proje var mı? Birlikte harika bir şey oluşturalım.",
    "contact.description": "Yeni projeler, yaratıcı fikirler veya vizyonlarınızın bir parçası olma fırsatları hakkında tartışmaya her zaman açığım.",
    "contact.formTitle": "Bana Mesaj Gönderin",
    "contact.label.name": "Ad",
    "contact.label.email": "E-posta",
    "contact.label.message": "Mesaj",
    "contact.placeholder.name": "Adınız",
    "contact.placeholder.email": "your.email@example.com",
    "contact.placeholder.message": "Mesajınız...",
    "contact.button.submit": "Mesaj Gönder",
    "contact.button.sending": "Gönderiliyor...",
    "contact.info.email": "E-posta",
    "contact.info.phone": "Telefon",
    "contact.info.location": "Konum",
    "footer.description": "Yenilikçi mobil çözümler yaratan tutkulu Android geliştirici. Birlikte bir sonraki harika uygulamayı oluşturalım.",
    "footer.quickLinks": "Hızlı Bağlantılar",
    "footer.links.whyme": "Neden Ben",
    "footer.links.about": "Hakkında",
    "footer.links.projects": "Projeler",
    "footer.links.contact": "İletişim",
    "footer.connect": "Bağlan",
    "footer.allRightsReserved": "Tüm hakları saklıdır.",
    "projectDetail.backToProjects": "Projelere Dön",
    "projectDetail.notFound": "Proje Bulunamadı",
    "projectDetail.button.backToHome": "Ana Sayfaya Dön",
    "projectDetail.button.viewOnGithub": "GitHub'da Görüntüle",
    "projectDetail.button.viewOnPlayStore": "Play Store'da Görüntüle",
    "projectDetail.features": "Özellikler",
    "resume.backToHome": "Ana Sayfaya Dön",
    "resume.download": "Özgeçmiş İndir",
  },
  hi: {
    "nav.skills": "कौशल",
    "nav.projects": "प्रोजेक्ट",
    "nav.whyme": "मुझे क्यों चुनें",
    "nav.about": "के बारे में",
    "nav.contact": "संपर्क",
    "hero.badge": "प्रोजेक्ट के लिए उपलब्ध",
    "hero.title": "नमस्ते, मैं मुहम्मद सलमान हूँ",
    "hero.titleHighlight": "Android डेवलपर",
    "hero.description": "आधुनिक तकनीकों के साथ सुंदर और कार्यात्मक Android अनुप्रयोग बनाना। Kotlin, Jetpack Compose, Firebase और मापनीय मोबाइल समाधान बनाने में विशेषज्ञ।",
    "hero.primaryButton": "मेरे प्रोजेक्ट देखें",
    "hero.secondaryButton": "मुझसे संपर्क करें",
    "hero.downloadResume": "रिज्यूमे डाउनलोड करें",
    "hero.viewResume": "रिज्यूमे देखें",
    "hero.feature1": "3+ वर्ष का अनुभव",
    "hero.feature2": "20+ प्रकाशित ऐप",
    "skills.title": "प्रौद्योगिकियाँ और उपकरण",
    "skills.subtitle": "आधुनिक उपकरण और प्रौद्योगिकियाँ जिनका उपयोग मैं असाधारण Android अनुप्रयोग बनाने के लिए करता हूँ",
    "projects.title": "विशेष प्रोजेक्ट",
    "projects.subtitle": "मेरे हाल के Android अनुप्रयोगों और मोबाइल प्रोजेक्टों की एक प्रदर्शनी",
    "projects.button.github": "GitHub",
    "projects.button.playStore": "Play Store",
    "projects.button.details": "विवरण",
    "about.subtitle": "मेरे बारे में",
    "about.title": "मुझे क्यों चुनें",
    "about.description": "मेरे पास Android विकास में वर्षों का अनुभव है, उच्च गुणवत्ता वाले मोबाइल अनुप्रयोग प्रदान करता हूँ जो अपेक्षाओं को पार करते हैं।",
    "about.stats.publishedApps": "प्रकाशित ऐप",
    "about.stats.projectsCompleted": "पूर्ण प्रोजेक्ट",
    "about.stats.yearsExperience": "वर्ष का अनुभव",
    "about.stats.averageRating": "औसत रेटिंग",
    "process.title": "मेरी विकास प्रक्रिया",
    "process.subtitle": "उच्च गुणवत्ता वाले Android अनुप्रयोग प्रदान करने के लिए एक संरचित दृष्टिकोण",
    "process.step1.title": "खोज",
    "process.step1.description": "विस्तृत परामर्श के माध्यम से आपकी आवश्यकताओं, लक्षित दर्शकों और व्यावसायिक लक्ष्यों को समझना।",
    "process.step2.title": "डिज़ाइन",
    "process.step2.description": "Material Design दिशानिर्देशों के साथ संरेखित सहज UI/UX डिज़ाइन और सिस्टम आर्किटेक्चर बनाना।",
    "process.step3.title": "विकास",
    "process.step3.description": "आधुनिक प्रौद्योगिकियों और सर्वोत्तम अभ्यासों का उपयोग करके मजबूत, मापनीय Android अनुप्रयोग बनाना।",
    "process.step4.title": "तैनाती",
    "process.step4.description": "पूर्ण परीक्षण, Play Store में सबमिशन, और निरंतर रखरखाव और अपडेट।",
    "reviews.title": "ग्राहक प्रशंसापत्र",
    "reviews.subtitle": "ग्राहक मेरे साथ काम करने के बारे में क्या कहते हैं",
    "contact.subtitle": "संपर्क करें",
    "contact.title": "क्या आपके मन में कोई प्रोजेक्ट है? आइए मिलकर कुछ अद्भुत बनाएं।",
    "contact.description": "मैं हमेशा नए प्रोजेक्ट, रचनात्मक विचारों या आपकी दृष्टि का हिस्सा बनने के अवसरों पर चर्चा के लिए खुला हूँ।",
    "contact.formTitle": "मुझे एक संदेश भेजें",
    "contact.label.name": "नाम",
    "contact.label.email": "ईमेल",
    "contact.label.message": "संदेश",
    "contact.placeholder.name": "आपका नाम",
    "contact.placeholder.email": "your.email@example.com",
    "contact.placeholder.message": "आपका संदेश...",
    "contact.button.submit": "संदेश भेजें",
    "contact.button.sending": "भेजा जा रहा है...",
    "contact.info.email": "ईमेल",
    "contact.info.phone": "फ़ोन",
    "contact.info.location": "स्थान",
    "footer.description": "नवाचारी मोबाइल समाधान बनाने वाला भावुक Android डेवलपर। आइए मिलकर अगला महान ऐप बनाएं।",
    "footer.quickLinks": "त्वरित लिंक",
    "footer.links.whyme": "मुझे क्यों चुनें",
    "footer.links.about": "के बारे में",
    "footer.links.projects": "प्रोजेक्ट",
    "footer.links.contact": "संपर्क",
    "footer.connect": "जुड़ें",
    "footer.allRightsReserved": "सभी अधिकार सुरक्षित।",
    "projectDetail.backToProjects": "प्रोजेक्ट पर वापस जाएं",
    "projectDetail.notFound": "प्रोजेक्ट नहीं मिला",
    "projectDetail.button.backToHome": "होम पर वापस जाएं",
    "projectDetail.button.viewOnGithub": "GitHub पर देखें",
    "projectDetail.button.viewOnPlayStore": "Play Store पर देखें",
    "projectDetail.features": "विशेषताएं",
    "resume.backToHome": "होम पर वापस जाएं",
    "resume.download": "रिज्यूमे डाउनलोड करें",
  },
  ur: {
    "nav.skills": "مہارتیں",
    "nav.projects": "منصوبے",
    "nav.whyme": "مجھے کیوں منتخب کریں",
    "nav.about": "میرے بارے میں",
    "nav.contact": "رابطہ",
    "hero.badge": "منصوبوں کے لیے دستیاب",
    "hero.title": "ہیلو، میں محمد سلمان ہوں",
    "hero.titleHighlight": "اینڈرائیڈ ڈویلپر",
    "hero.description": "جدید ٹیکنالوجیز کے ساتھ خوبصورت اور فعال اینڈرائیڈ ایپلیکیشنز بنانا۔ Kotlin، Jetpack Compose، Firebase میں مہارت، اور پیمانے پر موبائل حل بنانا۔",
    "hero.primaryButton": "میرے منصوبے دیکھیں",
    "hero.secondaryButton": "مجھ سے رابطہ کریں",
    "hero.downloadResume": "ریزیومے ڈاؤن لوڈ کریں",
    "hero.viewResume": "ریزیومے دیکھیں",
    "hero.feature1": "3+ سال کا تجربہ",
    "hero.feature2": "20+ شائع شدہ ایپس",
    "skills.title": "ٹیکنالوجیز اور ٹولز",
    "skills.subtitle": "جدید ٹولز اور ٹیکنالوجیز جو میں شاندار اینڈرائیڈ ایپلیکیشنز بنانے کے لیے استعمال کرتا ہوں",
    "projects.title": "نمایاں منصوبے",
    "projects.subtitle": "میری حالیہ اینڈرائیڈ ایپلیکیشنز اور موبائل منصوبوں کی نمائش",
    "projects.button.github": "GitHub",
    "projects.button.playStore": "Play Store",
    "projects.button.details": "تفصیلات",
    "about.subtitle": "میرے بارے میں",
    "about.title": "مجھے کیوں منتخب کریں",
    "about.description": "میرے پاس اینڈرائیڈ ڈویلپمنٹ میں سالوں کا تجربہ ہے، اعلیٰ معیار کی موبائل ایپلیکیشنز فراہم کرنا جو توقعات سے بھی بہتر ہیں۔",
    "about.stats.publishedApps": "شائع شدہ ایپس",
    "about.stats.projectsCompleted": "مکمل شدہ منصوبے",
    "about.stats.yearsExperience": "سال کا تجربہ",
    "about.stats.averageRating": "اوسط درجہ بندی",
    "process.title": "میرا ڈویلپمنٹ پروسس",
    "process.subtitle": "اعلیٰ معیار کی اینڈرائیڈ ایپلیکیشنز فراہم کرنے کا ایک منظم طریقہ",
    "process.step1.title": "دریافت",
    "process.step1.description": "تفصیلی مشاورت کے ذریعے آپ کی ضروریات، ہدف سامعین اور کاروباری اہداف کو سمجھنا۔",
    "process.step2.title": "ڈیزائن",
    "process.step2.description": "Material Design کی رہنمائیوں کے مطابق بدیہی UI/UX ڈیزائنز اور سسٹم آرکیٹیکچر بنانا۔",
    "process.step3.title": "ترقی",
    "process.step3.description": "جدید ٹیکنالوجیز اور بہترین طریقوں کا استعمال کرتے ہوئے مضبوط، پیمانے پر اینڈرائیڈ ایپلیکیشنز بنانا۔",
    "process.step4.title": "تعیناتی",
    "process.step4.description": "مکمل جانچ، Play Store میں جمع کرائی، اور جاری دیکھ بھال اور اپڈیٹس۔",
    "reviews.title": "کلائنٹ کے جائزے",
    "reviews.subtitle": "کلائنٹ میرے ساتھ کام کرنے کے بارے میں کیا کہتے ہیں",
    "contact.subtitle": "رابطہ کریں",
    "contact.title": "کسی منصوبے کے بارے میں سوچ رہے ہیں؟ آئیں مل کر کچھ حیرت انگیز بنائیں۔",
    "contact.description": "میں ہمیشہ نئے منصوبوں، تخلیقی خیالات یا آپ کے وژن کا حصہ بننے کے مواقع پر بات چیت کے لیے کھلا ہوں۔",
    "contact.formTitle": "مجھے پیغام بھیجیں",
    "contact.label.name": "نام",
    "contact.label.email": "ای میل",
    "contact.label.message": "پیغام",
    "contact.placeholder.name": "آپ کا نام",
    "contact.placeholder.email": "your.email@example.com",
    "contact.placeholder.message": "آپ کا پیغام...",
    "contact.button.submit": "پیغام بھیجیں",
    "contact.button.sending": "بھیج رہے ہیں...",
    "contact.info.email": "ای میل",
    "contact.info.phone": "فون",
    "contact.info.location": "مقام",
    "footer.description": "پرجوش اینڈرائیڈ ڈویلپر جو جدت پسند موبائل حل تخلیق کر رہا ہے۔ آئیں مل کر اگلی عظیم ایپ بنائیں۔",
    "footer.quickLinks": "فوری لنکس",
    "footer.links.whyme": "مجھے کیوں منتخب کریں",
    "footer.links.about": "میرے بارے میں",
    "footer.links.projects": "منصوبے",
    "footer.links.contact": "رابطہ",
    "footer.connect": "جڑیں",
    "footer.allRightsReserved": "تمام حقوق محفوظ ہیں۔",
    "projectDetail.backToProjects": "منصوبوں پر واپس",
    "projectDetail.notFound": "منصوبہ نہیں ملا",
    "projectDetail.button.backToHome": "ہوم پر واپس",
    "projectDetail.button.viewOnGithub": "GitHub پر دیکھیں",
    "projectDetail.button.viewOnPlayStore": "Play Store پر دیکھیں",
    "projectDetail.features": "خصوصیات",
    "resume.backToHome": "ہوم پر واپس",
    "resume.download": "ریزیومے ڈاؤن لوڈ کریں",
  },
  nl: {
    "nav.skills": "Vaardigheden",
    "nav.projects": "Projecten",
    "nav.whyme": "Waarom Ik",
    "nav.about": "Over",
    "nav.contact": "Contact",
    "hero.badge": "Beschikbaar voor Projecten",
    "hero.title": "Hallo, ik ben Muhammad Salman",
    "hero.titleHighlight": "Android Ontwikkelaar",
    "hero.description": "Maken van mooie en functionele Android-applicaties met moderne technologieën. Gespecialiseerd in Kotlin, Jetpack Compose, Firebase en het bouwen van schaalbare mobiele oplossingen.",
    "hero.primaryButton": "Bekijk Mijn Projecten",
    "hero.secondaryButton": "Neem Contact Op",
    "hero.downloadResume": "CV Downloaden",
    "hero.viewResume": "CV Bekijken",
    "hero.feature1": "3+ Jaar Ervaring",
    "hero.feature2": "20+ Gepubliceerde Apps",
    "skills.title": "Technologieën & Tools",
    "skills.subtitle": "Moderne tools en technologieën die ik gebruik om uitzonderlijke Android-applicaties te bouwen",
    "projects.title": "Uitgelichte Projecten",
    "projects.subtitle": "Een showcase van mijn recente Android-applicaties en mobiele projecten",
    "projects.button.github": "GitHub",
    "projects.button.playStore": "Play Store",
    "projects.button.details": "Details",
    "about.subtitle": "Over Mij",
    "about.title": "Waarom Mij Kiezen",
    "about.description": "Ik breng jarenlange ervaring in Android-ontwikkeling mee, waarbij ik hoogwaardige mobiele applicaties lever die verwachtingen overtreffen.",
    "about.stats.publishedApps": "Gepubliceerde Apps",
    "about.stats.projectsCompleted": "Voltooide Projecten",
    "about.stats.yearsExperience": "Jaar Ervaring",
    "about.stats.averageRating": "Gemiddelde Beoordeling",
    "process.title": "Mijn Ontwikkelingsproces",
    "process.subtitle": "Een gestructureerde aanpak voor het leveren van hoogwaardige Android-applicaties",
    "process.step1.title": "Ontdekking",
    "process.step1.description": "Uw vereisten, doelgroep en zakelijke doelen begrijpen door middel van gedetailleerd overleg.",
    "process.step2.title": "Ontwerp",
    "process.step2.description": "Het creëren van intuïtieve UI/UX-ontwerpen en systeemarchitectuur die zijn afgestemd op Material Design-richtlijnen.",
    "process.step3.title": "Ontwikkeling",
    "process.step3.description": "Bouwen van robuuste, schaalbare Android-applicaties met moderne technologieën en best practices.",
    "process.step4.title": "Implementatie",
    "process.step4.description": "Grondig testen, indienen bij Play Store en voortdurend onderhoud en updates.",
    "reviews.title": "Klantbeoordelingen",
    "reviews.subtitle": "Wat klanten zeggen over werken met mij",
    "contact.subtitle": "Neem Contact Op",
    "contact.title": "Heeft u een project in gedachten? Laten we samen iets geweldigs bouwen.",
    "contact.description": "Ik sta altijd open voor het bespreken van nieuwe projecten, creatieve ideeën of mogelijkheden om deel uit te maken van uw visies.",
    "contact.formTitle": "Stuur mij een Bericht",
    "contact.label.name": "Naam",
    "contact.label.email": "E-mail",
    "contact.label.message": "Bericht",
    "contact.placeholder.name": "Uw naam",
    "contact.placeholder.email": "uw.email@voorbeeld.com",
    "contact.placeholder.message": "Uw bericht...",
    "contact.button.submit": "Bericht Verzenden",
    "contact.button.sending": "Verzenden...",
    "contact.info.email": "E-mail",
    "contact.info.phone": "Telefoon",
    "contact.info.location": "Locatie",
    "footer.description": "Gepassioneerde Android-ontwikkelaar die innovatieve mobiele oplossingen creëert. Laten we samen de volgende geweldige app bouwen.",
    "footer.quickLinks": "Snelle Links",
    "footer.links.whyme": "Waarom Ik",
    "footer.links.about": "Over",
    "footer.links.projects": "Projecten",
    "footer.links.contact": "Contact",
    "footer.connect": "Verbinden",
    "footer.allRightsReserved": "Alle rechten voorbehouden.",
    "projectDetail.backToProjects": "Terug naar Projecten",
    "projectDetail.notFound": "Project Niet Gevonden",
    "projectDetail.button.backToHome": "Terug naar Home",
    "projectDetail.button.viewOnGithub": "Bekijk op GitHub",
    "projectDetail.button.viewOnPlayStore": "Bekijk op Play Store",
    "projectDetail.features": "Functies",
    "resume.backToHome": "Terug naar Home",
    "resume.download": "CV Downloaden",
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const savedLang = localStorage.getItem("language") as Language | null
    return savedLang || "en"
  })

  useEffect(() => {
    localStorage.setItem("language", language)
  }, [language])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
  }

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key
  }

  const getLanguageInfo = (code: Language): LanguageInfo | undefined => {
    return languages.find((lang) => lang.code === code)
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getLanguageInfo }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
